diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Users/Geral/AppData/Local/Programs/Git/mingw64/etc/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.email=kevynlevi0@gmail.com
user.name=Kevyn Levi
safe.directory=C:/Users/Geral/Desktop/Nova pasta/dodo/flutter-estudo/financy_app
credential.helper=cache
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.upstream.url=https://github.com/kevynlevii/primeiro_site.git
remote.upstream.fetch=+refs/heads/*:refs/remotes/upstream/*
remote.origin.url=https://github.com/InstitutodePesquisaINPES/fraldario_pmvc.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.main.remote=origin
branch.main.merge=refs/heads/main
